# Generated by Django 4.1.4 on 2023-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=15, verbose_name='Производитель оборудования')),
                ('model', models.CharField(max_length=20, verbose_name='Модель оборудования')),
                ('soft_version', models.IntegerField(max_length=10, verbose_name='Версия прошивки')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Серийный номер')),
                ('ip', models.IntegerField(max_length=16, verbose_name='IP-адрес')),
                ('location', models.CharField(max_length=30, verbose_name='Местонахождения')),
                ('buiding', models.CharField(max_length=10, verbose_name='Здание')),
            ],
        ),
    ]
