# Generated by Django 4.1.4 on 2023-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_switches_ip_alter_switches_soft_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switches',
            options={'verbose_name': 'Коммутаторы', 'verbose_name_plural': 'Коммутаторы'},
        ),
        migrations.AlterField(
            model_name='switches',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='switches',
            name='soft_version',
            field=models.CharField(max_length=20, verbose_name='Версия прошивки'),
        ),
    ]
