# Generated by Django 4.1.4 on 2023-01-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_switches_options_alter_switches_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switches',
            name='name',
            field=models.CharField(default='temp', max_length=30, verbose_name='Название'),
        ),
    ]
