# Generated by Django 4.1.4 on 2023-01-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_switches_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switches',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
